#### try...catch

`try...catch` 语句标记要尝试的语句块，并指定一个出现异常时抛出的响应。

```js
try {
   try_statements // 需要被执行的语句
}
[catch (exception_var_1 if condition_1) { // non-standard
    // exception_var_1 用于保存关联 catch 子句的异常对象的标识符
    // condition_1 一个条件表达式
   catch_statements_1 // 如果在 try 块里有异常被抛出时执行的语句
}]
...
[catch (exception_var_2) {
    // exception_var_2 用于保存关联 catch 子句的异常对象的标识符
   catch_statements_2 // 如果在 try 块里有异常被抛出时执行的语句
}]
[finally {
   finally_statements // 在 try 语句块之后执行的语句块，无论是否有异常抛出或捕获，这些语句都将执行
}]
```

`try`语句包含了由一个或者多个语句组成的`try`块，和一个`catch`块或者一个`finally`块，或者两个兼有，下面是三种形式的`try`声明：

1. `try...catch`
2. `try...finally`
3. `try...catch...finally`

`catch`子句包含`try`块中抛出异常时要执行的语句。也就是，你想让`try`语句中的内容成功，如果没成功，你想控制接下来发生的事情，这时你可以在`catch`语句中实现。

如果在`try`块中有任何一个语句（或者从`try`块中调用的函数）抛出异常，控制立即转向`catch`子句。

如果在`try`块中没有异常抛出，会跳过`catch`子句。

`finally`子句在`try`块和`catch`块之后执行，但是在下一个`try`声明之前执行。无论是否有异常抛出或捕获它总是执行。

你可以嵌套一个或者更多的`try`语句。如果内部的`try`语句没有`catch`子句，那么将会进入包裹它的`try`语句的`catch`子句。







































